<!--
  This enabled central package management. 
  This allows for controling all NuGet packages within the Directory.Packages.props file
  See https://learn.microsoft.com/nuget/consume-packages/Central-Package-Management
  -->
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
    <!--
  This defines the set of centrally managed packages.
  This would typically list all NuGet packages used within this solution.
  -->
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.Azure.AppContainers" Version="13.2.4" />
    <PackageVersion Include="Aspire.Hosting.Azure.Functions" Version="13.2.4" />
    <PackageVersion Include="Aspire.Hosting.JavaScript" Version="13.2.4" />
    <PackageVersion Include="Azure.Identity" Version="1.21.0" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.McpInspector" Version="13.2.1-beta.532" />
    <PackageVersion Include="Microsoft.ApplicationInsights.WorkerService" Version="3.1.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.50.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Mcp" Version="1.5.0-preview.1" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Mcp.Sdk" Version="1.0.0-preview.4" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.8.1" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.5.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.5.0" />
    <PackageVersion Include="Microsoft.Graph" Version="5.105.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
    <PackageVersion Include="QRCoder" Version="1.8.0" />
  </ItemGroup>
</Project>
